/** from the mdn docs https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values */
export enum KeyCode {
	/* ===== Letters ===== */
	KeyA = 'KeyA',
	KeyB = 'KeyB',
	KeyC = 'KeyC',
	KeyD = 'KeyD',
	KeyE = 'KeyE',
	KeyF = 'KeyF',
	KeyG = 'KeyG',
	KeyH = 'KeyH',
	KeyI = 'KeyI',
	KeyJ = 'KeyJ',
	KeyK = 'KeyK',
	KeyL = 'KeyL',
	KeyM = 'KeyM',
	KeyN = 'KeyN',
	KeyO = 'KeyO',
	KeyP = 'KeyP',
	KeyQ = 'KeyQ',
	KeyR = 'KeyR',
	KeyS = 'KeyS',
	KeyT = 'KeyT',
	KeyU = 'KeyU',
	KeyV = 'KeyV',
	KeyW = 'KeyW',
	KeyX = 'KeyX',
	KeyY = 'KeyY',
	KeyZ = 'KeyZ',

	/* ===== Digits ===== */
	Digit0 = 'Digit0',
	Digit1 = 'Digit1',
	Digit2 = 'Digit2',
	Digit3 = 'Digit3',
	Digit4 = 'Digit4',
	Digit5 = 'Digit5',
	Digit6 = 'Digit6',
	Digit7 = 'Digit7',
	Digit8 = 'Digit8',
	Digit9 = 'Digit9',

	/* ===== Function Keys ===== */
	F1 = 'F1',
	F2 = 'F2',
	F3 = 'F3',
	F4 = 'F4',
	F5 = 'F5',
	F6 = 'F6',
	F7 = 'F7',
	F8 = 'F8',
	F9 = 'F9',
	F10 = 'F10',
	F11 = 'F11',
	F12 = 'F12',
	F13 = 'F13',
	F14 = 'F14',
	F15 = 'F15',
	F16 = 'F16',
	F17 = 'F17',
	F18 = 'F18',
	F19 = 'F19',
	F20 = 'F20',
	F21 = 'F21',
	F22 = 'F22',
	F23 = 'F23',
	F24 = 'F24',

	/* ===== Numpad ===== */
	Numpad0 = 'Numpad0',
	Numpad1 = 'Numpad1',
	Numpad2 = 'Numpad2',
	Numpad3 = 'Numpad3',
	Numpad4 = 'Numpad4',
	Numpad5 = 'Numpad5',
	Numpad6 = 'Numpad6',
	Numpad7 = 'Numpad7',
	Numpad8 = 'Numpad8',
	Numpad9 = 'Numpad9',
	NumpadAdd = 'NumpadAdd',
	NumpadSubtract = 'NumpadSubtract',
	NumpadMultiply = 'NumpadMultiply',
	NumpadDecimal = 'NumpadDecimal',
	NumpadEqual = 'NumpadEqual',
	NumpadComma = 'NumpadComma',

	/* ===== Modifiers ===== */
	ShiftLeft = 'ShiftLeft',
	ShiftRight = 'ShiftRight',
	ControlLeft = 'ControlLeft',
	AltLeft = 'AltLeft',
	CapsLock = 'CapsLock',

	/* ===== Navigation / Editing ===== */
	Backspace = 'Backspace',
	Tab = 'Tab',
	Enter = 'Enter',
	Space = 'Space',
	Undo = 'Undo',
	Paste = 'Paste',

	/* ===== Symbols / Punctuation ===== */
	Minus = 'Minus',
	Equal = 'Equal',
	BracketLeft = 'BracketLeft',
	BracketRight = 'BracketRight',
	Semicolon = 'Semicolon',
	Quote = 'Quote',
	Backquote = 'Backquote',
	Backslash = 'Backslash',
	Slash = 'Slash',
	Comma = 'Comma',
	Period = 'Period',
	IntlBackslash = 'IntlBackslash',
	IntlRo = 'IntlRo',
	IntlYen = 'IntlYen',

	/* ===== Language / IME ===== */
	KanaMode = 'KanaMode',
	Lang1 = 'Lang1',
	Lang2 = 'Lang2',
	Lang3 = 'Lang3',
	Lang4 = 'Lang4',
	Convert = 'Convert',
	NonConvert = 'NonConvert',

	/* ===== Misc ===== */
	Escape = 'Escape',
	ScrollLock = 'ScrollLock',
	Pause = 'Pause',
	Unidentified = 'Unidentified'
}
